x-common:
  &common_settings
  image: quay.io/glidr/builder:golang1.22
  working_dir: /go/src/github.com/launchpadcentral/yip
  volumes:
    - ./main.go:/go/src/github.com/launchpadcentral/yip/main.go:rw
    - ./main_test.go:/go/src/github.com/launchpadcentral/yip/main_test.go:rw
    - ./go.mod:/go/src/github.com/launchpadcentral/yip/go.mod:rw
    - ./go.sum:/go/src/github.com/launchpadcentral/yip/go.sum:rw
    - ./tmp/:/tmp/:rw

services:
  yip:
    <<: *common_settings
    container_name: yip
    command: >
      bash -c "tail -f /dev/null"
    environment:
      - GOBIN=/usr/local/go/

  yip-test:
    <<: *common_settings
    container_name: yip-test
    command: >
      bash -c "go test"

  yip-build:
    <<: *common_settings
    container_name: yip-builder
    environment:
      - GOBIN=/usr/local/go/
      - GOOS=linux
      - GOARCH=amd64
      - RELEASE=0.2.0
    command: >
      bash -c "go get && GOOS=$$GOOS GOARCH=$$GOARCH go build -o /tmp/yip-$$RELEASE-$$GOOS-$$GOARCH"
