version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  codecov: codecov/codecov@3.2.0

jobs:
  build:
    working_directory: /go/src/github.com/launchpadcentral/yip
    docker:
    - image: quay.io/glidr/builder:golang1.15
      auth:
        username: $QUAY_USERNAME
        password: $QUAY_PASSWORD
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - run:
        name: Install JUnit
        command: |
          go get github.com/jstemmer/go-junit-report
    - run: mkdir -p /tmp/test-results
    - run:
        name: Install dependencies
        command: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go get -t -v ./...
    - run:
        name: Run unit tests
        command: |
          git clone git@github.com:launchpadcentral/cicd.git
          ./cicd/scripts/test_microservice.sh
          apk add --no-cache gnupg
    - codecov/upload:
        file: coverage.lcov
    - store_artifacts: # upload test coverage as artifact
         path: ./coverage.lcov
         prefix: tests

workflows:
  version: 2
  test-and-build:
    jobs:
      - build:
          context:
            - org-global
          filters:
            branches:
              only: master
