version: 2.1
orbs:
  codecov: codecov/codecov@5.0.3
  slack: circleci/slack@5.0.0

executors:
  golang:
    docker:
      - image: cimg/go:1.22.5
    working_directory: ~/project

commands:
  build_packages:
    parameters:
      goos:
        type: string
      goarch:
        type: string
    steps:
      - run:
          name: Build for << parameters.goos >> (<< parameters.goarch >>)
          command: GOOS=<< parameters.goos >> GOARCH=<< parameters.goarch >> go build -o /tmp/yip-<< parameters.goos >>-<< parameters.goarch >>
      - store_artifacts:
          path: /tmp/yip-<< parameters.goos >>-<< parameters.goarch >>
          destination: yip-<< parameters.goos >>-<< parameters.goarch >>

jobs:
  test:
    executor: golang
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run:
          name: Install JUnit
          command: go install github.com/jstemmer/go-junit-report@latest
      - run:
          name: Setup test environment
          command: mkdir -p ${TEST_RESULTS}
      - run:
          name: Run tests and collect coverage
          command: |
            ./scripts/test_microservice.sh
      - codecov/upload:
          files: ${TEST_RESULTS}/coverage.txt
      - store_artifacts:
          path: ${TEST_RESULTS}
          destination: test-results
      - store_test_results:
          path: ${TEST_RESULTS}

  build_package:
    parameters:
      goos:
        type: string
      goarch:
        type: string
    executor: golang
    steps:
      - checkout
      - build_packages:
          goos: << parameters.goos >>
          goarch: << parameters.goarch >>
      - persist_to_workspace:
          root: /tmp
          paths:
            - yip-<< parameters.goos >>-<< parameters.goarch >>

workflows:
  version: 2
  test-and-build:
    jobs:
      - test
      - build_package:
          name: build_darwin_amd64
          goos: darwin
          goarch: amd64
          requires:
            - test
      - build_package:
          name: build_darwin_arm64
          goos: darwin
          goarch: arm64
          requires:
            - test
      - build_package:
          name: build_linux_amd64
          goos: linux
          goarch: amd64
          requires:
            - test

