version: 2
jobs:
  build:
    working_directory: /go/src/github.com/launchpadcentral/yip
    docker:
    - image: quay.io/glidr/builder:golang1.15
      auth:
        username: $QUAY_USERNAME
        password: $QUAY_PASSWORD
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - run:
        name: Install JUnit
        command: |
          go get github.com/jstemmer/go-junit-report
    - run: mkdir -p /tmp/test-results
    - run:
        name: Install dependencies
        command: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go get -t -v ./...
    - run:
        name: Run unit tests
        command: |
          git clone git@github.com:launchpadcentral/cicd.git
          ./cicd/scripts/test_microservice.sh
          bash <(curl -s https://codecov.io/bash) -t 3b7f7b0d-5ae5-4e80-85ed-9833aefd8a2e
    - store_test_results:
        path: /tmp/test-results
    - slack/status:
        fail_only: true
        webhook: $SLACKWEBHOOK

workflows:
  version: 2
  test-and-build:
    jobs:
      - build:
          filters:
            branches:
              only: master
